# Generated by Django 4.1.5 on 2023-09-01 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoery",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cdate", models.DateField(auto_now=True)),
                ("update", models.DateField(auto_now=True)),
                ("categoery_name", models.CharField(max_length=100)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Qusetion",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cdate", models.DateField(auto_now=True)),
                ("update", models.DateField(auto_now=True)),
                ("categoery_qstn", models.CharField(max_length=100)),
                ("makrs", models.IntegerField(default=5)),
                (
                    "ctrgy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoery",
                        to="demapp.categoery",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cdate", models.DateField(auto_now=True)),
                ("update", models.DateField(auto_now=True)),
                ("answ", models.CharField(max_length=100)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_answers",
                        to="demapp.qusetion",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
